sonarr:
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
  rootfolder:
    - name: Series
      path: /data
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
  downloadclient:
    - name: Transmission
      enable: true
      protocol: torrent
      fields:
        - name: host
          value: transmission
        - name: port
          value: 9091
      implementation: Transmission
      configContract: TransmissionSettings
radarr:
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
  rootfolder:
    - name: Movies
      path: /data
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
  downloadclient:
    - name: Transmission
      enable: true
      protocol: torrent
      fields:
        - name: host
          value: transmission
        - name: port
          value: 9091
      implementation: Transmission
      configContract: TransmissionSettings
lidarr:
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
  rootfolder:
    - name: Music
      path: /data
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
  downloadclient:
    - name: Transmission
      enable: true
      protocol: torrent
      fields:
        - name: host
          value: transmission
        - name: port
          value: 9091
      implementation: Transmission
      configContract: TransmissionSettings
readarr:
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
  rootfolder:
    - name: Books
      path: /data
      defaultTags: []
  downloadclient:
    - name: Transmission
      enable: true
      protocol: torrent
      fields:
        - name: host
          value: transmission
        - name: port
          value: 9091
      implementation: Transmission
      configContract: TransmissionSettings
prowlarr:
  config:
    host:
      analyticsEnabled: false
    ui:
      theme: dark
  indexer:
    - name: Internet Archive
      enable: true
      definitionName: internetarchive
      implementation: Cardigann
      configContract: CardigannSettings
      fields: # What fields are needed for each indexer is a bit obscure.
        - name: definitionFile
          value: internetarchive
        - name: titleOnly
          value: true
        - name: noMagnet
          value: false
        - name: sort
          value: 2
        - name: type
          value: 1
      tags: []
  applications:
    - name: Sonarr
      syncLevel: addOnly
      implementation: Sonarr
      configContract: SonarrSettings
      fields:
        - name: prowlarrUrl
          value: http://192.168.178.65:9696
        - name: baseUrl
          value: http://192.168.178.65:8989
        - name: apiKey
          value: 155dc8530b5e41159a9a54fce470ea22
    - name: Radarr
      syncLevel: addOnly
      implementation: Radarr
      configContract: RadarrSettings
      fields:
        - name: prowlarrUrl
          value: http://192.168.178.65:9696
        - name: baseUrl
          value: http://192.168.178.65:7878
        - name: apiKey
          value: be3f73d43ad94d42af8c5442464c1c9e
    - name: Lidarr
      syncLevel: addOnly
      implementation: Lidarr
      configContract: LidarrSettings
      fields:
        - name: prowlarrUrl
          value: http://192.168.178.65:9696
        - name: baseUrl
          value: http://192.168.178.65:8686
        - name: apiKey
          value: 6535bf69ff504ab79dea59790e88d2e6
    - name: Readarr
      syncLevel: addOnly
      implementation: Readarr
      configContract: ReadarrSettings
      fields:
        - name: prowlarrUrl
          value: http://192.168.178.65:9696
        - name: baseUrl
          value: http://192.168.178.65:8787
        - name: apiKey
          value: ef11e3c4e4484c429e6a5fadb19491f2
